export const REQUEST_GET_FILEINFO = 'REQUEST_GET_FILEINFO';
export const GET_FILEINFO_SUCCEEDED = 'GET_FILEINFO_SUCCEEDED';
export const GET_FILEINFO_FAILED = 'GET_FILEINFO_FAILED';
export const REQUEST_GET_FILEEXTENT = 'REQUEST_GET_FILEEXTENT';
export const GET_FILEEXTENT_SUCCEEDED = 'GET_FILEEXTENT_SUCCEEDED';
export const GET_FILEEXTENT_FAILED = 'GET_FILEEXTENT_FAILED';

