export const REQUEST_GET_FILEINFO = 'REQUEST_GET_FILEINFO';
export const GET_FILEINFO_SUCCEEDED = 'GET_FILEINFO_SUCCEEDED';
export const GET_FILEINFO_FAILED = 'GET_FILEINFO_FAILED';
export const REQUEST_GET_FILEEXTENT = 'REQUEST_GET_FILEEXTENT';
export const GET_FILEEXTENT_SUCCEEDED = 'GET_FILEEXTENT_SUCCEEDED';
export const GET_FILEEXTENT_FAILED = 'GET_FILEEXTENT_FAILED';

export const REQUEST_GET_DB_ENTRIES = 'REQUEST_GET_DB_ENTRIES';
export const GET_DB_ENTRIES_SUCCEEDED = 'GET_DB_ENTRIES_SUCCEEDED';
export const GET_DB_ENTRIES_FAILED = 'GET_DB_ENTRIES_FAILED';

export const REQUEST_DROP_DB = 'REQUEST_DROP_DB';
export const DROP_DB_SUCCEEDED = 'DROP_DB_SUCCEEDED';
export const DROP_DB_FAILED = 'DROP_DB_FAILED';



